<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA5zppxv\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA5zppxv/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerA5zppxv.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerA5zppxv\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerA5zppxv\appProdProjectContainer([
    'container.build_hash' => 'A5zppxv',
    'container.build_id' => 'd6c2694c',
    'container.build_time' => 1609866734,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerA5zppxv');
